### ISSUE TITLE
Failed to connect to docker

### ISSUE THREAD

**Issue by azyshalom** [fsouza/go-dockerclient#622] opened 2017-02-12 07:14 UTC
Failed to connect to docker using the example:
Get http://unix.sock/images/json?: dial tcp: lookup unix.sock on 172.31.0.2:53: no such host
`
# go version
go version go1.7.3 linux/amd64

# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 25
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-106-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.305 GiB
Name: ip-172-31-2-198
ID: 3RU6:PZJL:RDDY:CNJO:F2RR:NIFO:JOFP:UXE2:PALK:EXUW:DHAZ:SRRO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jerbi
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
 
# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

`

**Comment by azyshalom** [comment] 2017-02-12 13:18
Tested on coreos and centos, same error

**Comment by faryon93** [comment] 2017-02-12 14:00
same error on debian jessie

**Comment by hrzbrg** [comment] 2017-02-12 19:47
#621 should solve it

**Comment by faide** [comment] 2017-02-12 20:11
can people having this issue test my PR and see if it works for them ?

**Comment by hrzbrg** [comment] 2017-02-12 20:13
Just applied it and build it. Works for me together with Registrator.
Thanks 👍

**Comment by niko83** [comment] 2017-02-13 13:52
Reason of this issue is last change https://github.com/hashicorp/go-cleanhttp/commit/a45970658e51fea2c41445ff0f7e07106d007617

Temporary workaround:
1) create folder 
vendor/github.com/fsouza/go-dockerclient 
with master content of this repo

and create folder

vendor/github.com/hashicorp/go-cleanhttp
with version of source files https://github.com/hashicorp/go-cleanhttp/tree/ad28ea4487f05916463e2423a55166280e8254b5

**Comment by fsouza** [comment] 2017-02-14 00:57
@azyshalom now that #621 is merged, can you check if the issue is gone? Thanks!

**Comment by azyshalom** [comment] 2017-02-14 04:52
Works great! thanks

**Comment by fsouza** [comment] 2017-02-14 05:27
Nice, thank you for confirming!

**Closed by fsouza** 2017-02-14 05:27 UTC

**Comment by azyshalom** [comment] 2017-02-17 07:29
@fsouza i still see this error on coreos 1235, docker 1.12.6.
it works fine on other platforms.
is it possible that http still use tr.Dial instead of tr.DialContext? i see that the code still exists.
Thanks.
