### ISSUE TITLE
Unable to download with `go get`

### ISSUE THREAD

**Issue by divideandconquer** [fsouza/go-dockerclient#199] opened 2015-01-07 21:34 UTC
It looks like docker/pkg/archive was [updated](https://github.com/docker/docker/commit/6d801a3caa54ad7ef574bc426aa1ffc412c5af82).  Excludes is now ExcludePatterns. 
https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L32

```sh
go get github.com/fsouza/go-dockerclient
# github.com/fsouza/go-dockerclient
../../../github.com/fsouza/go-dockerclient/tar.go:30: unknown archive.TarOptions field 'Excludes' in struct literal
```

**Comment by rafecolton** [comment] 2015-01-08 05:06
Duplicate of https://github.com/fsouza/go-dockerclient/pull/195 and https://github.com/fsouza/go-dockerclient/pull/196 - @fsouza, anything?

**Comment by heavenlyhash** [comment] 2015-01-08 10:22
And #194.

Four issues and multiple redundant PRs opened within five hours of each other, because two unrelated people on the internet didn't push at the same time when one of them updated some keywords?  I'm linking to this thread the next time someone says `go get` is an acceptable way to do business; it's a downright coup de grâce.

Anyone experiencing a problem right now: Might I recommend thinking about setting up your workspace and toolchains with something that doesn't put you at the whims of someone else's HTTP server?

**Comment by fsouza** [comment] 2015-01-09 01:24
It's fixed now, thank you! Sorry for the delay, I'm out these days.

@heavenlyhash in [tsuru](/tsuru/tsuru) we use Godeps to pin go-dockerclient and go-dockerclient's dependencies. I might write something related to it in go-dockerclient's README.

**Closed by fsouza** 2015-01-09 01:24 UTC
