### ISSUE TITLE
Question: Do you have a plan to support ssh?

### ISSUE THREAD

**Issue by skanehira** [fsouza/go-dockerclient#772] opened 2019-02-04 14:21 UTC
I want to use ssh client to connect docker engine but it seems not support ssh now.
Do you have a plan to support ssh?

**Comment by fsouza** [comment] 2019-02-09 02:46
Hey @skanehira, sorry for the delayed response. This is out of scope for this package, you'd probably need to wrap it with some ssh client library.

**Closed by fsouza** 2019-02-09 02:46 UTC

**Comment by skanehira** [comment] 2019-02-10 03:03
@fsouza 
Thanks :)

**Comment by stokito** [comment] 2021-06-23 20:01
Duplicate of #815

**Comment by alexpts** [comment] 2023-09-23 09:54
Are there any improvements?
